version: "3.8"

services:
  service:
    build:
      context: .
      ssh:
        - default=${GM_SDK_GIT_SSH_KEY:-$HOME/.ssh/id_rsa}
    image: wealth_management:latest
    restart: unless-stopped
    ports:
      - "1022:7688"