[tool.poetry]
name = "thought-agent"
version = "0.1.0"
description = ""
authors = ["Dan Chen <dchen@thoughtworks.com>"]
readme = "README.md"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
default= true

[tool.poetry.dependencies]
python = "^3.9"
loguru = "^0.7.2"
schedule = "^1.2.1"
parameterized = "0.8.1"
chinese2digits = "^6.0.2"
colorama = "^0.4.6"
openai = "1.3.7"
ruff = "^0.1.9"
black = "^23.12.1"
sse-starlette = "^1.8.2"
fastapi = "0.108.0"
lancedb = "0.4.3"
pymilvus = "2.2.4"
tabulate = "^0.9.0"
python-pptx = "^0.6.23"
gluon-meson-sdk = {git = "git@github.com:gluon-meson/GluonMeson-SDK.git", rev = "hsbc-tb-guru56"}
GluonMeson-Component-SDK = {git = "git@github.com:gluon-meson/GluonMeson-Component-SDK.git", tag = "v0.0.3"}
psycopg-pool = "^3.2.1"
psycopg = "^3.1.18"
greenlet = "^3.0.3"
tiktoken = "^0.6.0"
dateparser = "^1.2.0"
streamlit-code-editor = "^0.1.12"
streamlit = "1.12.0"
streamlit-tree-select = "^0.0.5"
altair = "<5"
openpyxl = "^3.1.2"



[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
pre-commit = "^3.6.0"
pytest-html = "^4.1.1"
openpyxl = "^3.1.2"
click = "^8.1.7"
pytest-asyncio = "^0.23.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
