@startuml

[*] --> ReAct: 收到用户输入
ReAct --> 动作执行 : 执行
动作执行 --> [*] : 输出答案

state ReAct {
意图识别 --> 槽填充 : 成功
意图识别 : QA, 闲聊, ...
意图识别 --> 策略选择 : 意图不明
槽填充 --> 策略选择 : 选择执行策略
}

state 动作执行 {
    [*] --> 问答: QA
    问答 : eg. 产品条款
    [*] --> NLG : Others
    NLG : eg. 追问, 闲聊, 澄清...
    [*] --> 计算 : Calculation
    计算: eg. 保费
    [*] --> 查询 : Query
    查询: eg. 核保/保单状态
}

@enduml